/* automatically generated by rust-bindgen 0.72.1 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 40;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_dnsquestion_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_dnsresponse_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_servers_list_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_server_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_ednsoption {
    pub optionCode: u16,
    pub len: u16,
    pub data: *const ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dnsdist_ffi_ednsoption"][::std::mem::size_of::<dnsdist_ffi_ednsoption>() - 16usize];
    ["Alignment of dnsdist_ffi_ednsoption"]
        [::std::mem::align_of::<dnsdist_ffi_ednsoption>() - 8usize];
    ["Offset of field: dnsdist_ffi_ednsoption::optionCode"]
        [::std::mem::offset_of!(dnsdist_ffi_ednsoption, optionCode) - 0usize];
    ["Offset of field: dnsdist_ffi_ednsoption::len"]
        [::std::mem::offset_of!(dnsdist_ffi_ednsoption, len) - 2usize];
    ["Offset of field: dnsdist_ffi_ednsoption::data"]
        [::std::mem::offset_of!(dnsdist_ffi_ednsoption, data) - 8usize];
};
pub type dnsdist_ffi_ednsoption_t = dnsdist_ffi_ednsoption;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_http_header {
    pub name: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dnsdist_ffi_http_header"][::std::mem::size_of::<dnsdist_ffi_http_header>() - 16usize];
    ["Alignment of dnsdist_ffi_http_header"]
        [::std::mem::align_of::<dnsdist_ffi_http_header>() - 8usize];
    ["Offset of field: dnsdist_ffi_http_header::name"]
        [::std::mem::offset_of!(dnsdist_ffi_http_header, name) - 0usize];
    ["Offset of field: dnsdist_ffi_http_header::value"]
        [::std::mem::offset_of!(dnsdist_ffi_http_header, value) - 8usize];
};
pub type dnsdist_ffi_http_header_t = dnsdist_ffi_http_header;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_tag {
    pub name: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dnsdist_ffi_tag"][::std::mem::size_of::<dnsdist_ffi_tag>() - 16usize];
    ["Alignment of dnsdist_ffi_tag"][::std::mem::align_of::<dnsdist_ffi_tag>() - 8usize];
    ["Offset of field: dnsdist_ffi_tag::name"]
        [::std::mem::offset_of!(dnsdist_ffi_tag, name) - 0usize];
    ["Offset of field: dnsdist_ffi_tag::value"]
        [::std::mem::offset_of!(dnsdist_ffi_tag, value) - 8usize];
};
pub type dnsdist_ffi_tag_t = dnsdist_ffi_tag;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_raw_value {
    pub value: *const ::std::os::raw::c_char,
    pub size: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dnsdist_ffi_raw_value"][::std::mem::size_of::<dnsdist_ffi_raw_value>() - 16usize];
    ["Alignment of dnsdist_ffi_raw_value"]
        [::std::mem::align_of::<dnsdist_ffi_raw_value>() - 8usize];
    ["Offset of field: dnsdist_ffi_raw_value::value"]
        [::std::mem::offset_of!(dnsdist_ffi_raw_value, value) - 0usize];
    ["Offset of field: dnsdist_ffi_raw_value::size"]
        [::std::mem::offset_of!(dnsdist_ffi_raw_value, size) - 8usize];
};
pub type dnsdist_ffi_raw_value_t = dnsdist_ffi_raw_value;
pub const dnsdist_ffi_protocol_type_dnsdist_ffi_protocol_type_doudp: dnsdist_ffi_protocol_type = 0;
pub const dnsdist_ffi_protocol_type_dnsdist_ffi_protocol_type_dotcp: dnsdist_ffi_protocol_type = 1;
pub const dnsdist_ffi_protocol_type_dnsdist_ffi_protocol_type_dnscryptudp:
    dnsdist_ffi_protocol_type = 2;
pub const dnsdist_ffi_protocol_type_dnsdist_ffi_protocol_type_dnscrypttcp:
    dnsdist_ffi_protocol_type = 3;
pub const dnsdist_ffi_protocol_type_dnsdist_ffi_protocol_type_dot: dnsdist_ffi_protocol_type = 4;
pub const dnsdist_ffi_protocol_type_dnsdist_ffi_protocol_type_doh: dnsdist_ffi_protocol_type = 5;
pub type dnsdist_ffi_protocol_type = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_localaddr(
        dq: *const dnsdist_ffi_dnsquestion_t,
        addr: *mut *const ::std::os::raw::c_void,
        addrSize: *mut usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_local_port(dq: *const dnsdist_ffi_dnsquestion_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_is_remote_v6(
        dnsQuestion: *const dnsdist_ffi_dnsquestion_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_remoteaddr(
        dq: *const dnsdist_ffi_dnsquestion_t,
        addr: *mut *const ::std::os::raw::c_void,
        addrSize: *mut usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_masked_remoteaddr(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        addr: *mut *const ::std::os::raw::c_void,
        addrSize: *mut usize,
        bits: u8,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_remote_port(dq: *const dnsdist_ffi_dnsquestion_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_incoming_interface(
        dnsQuestion: *const dnsdist_ffi_dnsquestion_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_qname_raw(
        dq: *const dnsdist_ffi_dnsquestion_t,
        qname: *mut *const ::std::os::raw::c_char,
        qnameSize: *mut usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_qname_hash(
        dq: *const dnsdist_ffi_dnsquestion_t,
        init: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_qtype(dq: *const dnsdist_ffi_dnsquestion_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_qclass(dq: *const dnsdist_ffi_dnsquestion_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_id(dq: *const dnsdist_ffi_dnsquestion_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_rcode(
        dq: *const dnsdist_ffi_dnsquestion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_header(
        dq: *const dnsdist_ffi_dnsquestion_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_len(dq: *const dnsdist_ffi_dnsquestion_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_size(dq: *const dnsdist_ffi_dnsquestion_t) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_size(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        newSize: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_opcode(dq: *const dnsdist_ffi_dnsquestion_t) -> u8;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_tcp(dq: *const dnsdist_ffi_dnsquestion_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_protocol(
        dq: *const dnsdist_ffi_dnsquestion_t,
    ) -> dnsdist_ffi_protocol_type;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_skip_cache(dq: *const dnsdist_ffi_dnsquestion_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_use_ecs(dq: *const dnsdist_ffi_dnsquestion_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_ecs_override(dq: *const dnsdist_ffi_dnsquestion_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_ecs_prefix_length(
        dq: *const dnsdist_ffi_dnsquestion_t,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_is_temp_failure_ttl_set(
        dq: *const dnsdist_ffi_dnsquestion_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_temp_failure_ttl(
        dq: *const dnsdist_ffi_dnsquestion_t,
    ) -> u32;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_do(dnsQuestion: *const dnsdist_ffi_dnsquestion_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_edns_version(
        dnsQuestion: *const dnsdist_ffi_dnsquestion_t,
    ) -> u8;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_edns_extended_rcode(
        dnsQuestion: *const dnsdist_ffi_dnsquestion_t,
    ) -> u8;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_sni(
        dq: *const dnsdist_ffi_dnsquestion_t,
        sni: *mut *const ::std::os::raw::c_char,
        sniSize: *mut usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_tag(
        dq: *const dnsdist_ffi_dnsquestion_t,
        label: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_tag_raw(
        dq: *const dnsdist_ffi_dnsquestion_t,
        label: *const ::std::os::raw::c_char,
        buffer: *mut ::std::os::raw::c_char,
        bufferSize: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_http_path(
        dq: *mut dnsdist_ffi_dnsquestion_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_http_query_string(
        dq: *mut dnsdist_ffi_dnsquestion_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_http_host(
        dq: *mut dnsdist_ffi_dnsquestion_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_http_scheme(
        dq: *mut dnsdist_ffi_dnsquestion_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_mac_addr(
        dq: *const dnsdist_ffi_dnsquestion_t,
        buffer: *mut ::std::os::raw::c_void,
        bufferSize: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_elapsed_us(dq: *const dnsdist_ffi_dnsquestion_t) -> u64;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_edns_options(
        ref_: *mut dnsdist_ffi_dnsquestion_t,
        out: *mut *const dnsdist_ffi_ednsoption_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_http_headers(
        ref_: *mut dnsdist_ffi_dnsquestion_t,
        out: *mut *const dnsdist_ffi_http_header_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_tag_array(
        ref_: *mut dnsdist_ffi_dnsquestion_t,
        out: *mut *const dnsdist_ffi_tag_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_result(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        str_: *const ::std::os::raw::c_char,
        strSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_rcode(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        rcode: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_len(dq: *mut dnsdist_ffi_dnsquestion_t, len: u16);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_skip_cache(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        skipCache: bool,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_use_ecs(dq: *mut dnsdist_ffi_dnsquestion_t, useECS: bool);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_ecs_override(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        ecsOverride: bool,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_ecs_prefix_length(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        ecsPrefixLength: u16,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_temp_failure_ttl(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        tempFailureTTL: u32,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_unset_temp_failure_ttl(dq: *mut dnsdist_ffi_dnsquestion_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_tag(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        label: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_unset_tag(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        label: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_tag_raw(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        label: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        valueSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_requestor_id(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        value: *const ::std::os::raw::c_char,
        valueSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_device_id(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        value: *const ::std::os::raw::c_char,
        valueSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_device_name(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        value: *const ::std::os::raw::c_char,
        valueSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_http_response(
        ref_: *mut dnsdist_ffi_dnsquestion_t,
        statusCode: u16,
        body: *const ::std::os::raw::c_char,
        bodyLen: usize,
        contentType: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_extended_dns_error(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        infoCode: u16,
        extraText: *const ::std::os::raw::c_char,
        extraTextSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_add_extended_dns_error(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        infoCode: u16,
        extraText: *const ::std::os::raw::c_char,
        extraTextSize: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_trailing_data(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        out: *mut *const ::std::os::raw::c_char,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_trailing_data(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        data: *const ::std::os::raw::c_char,
        dataLen: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_send_trap(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        reason: *const ::std::os::raw::c_char,
        reasonLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_spoof_raw(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        values: *const dnsdist_ffi_raw_value_t,
        valuesCount: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_spoof_addrs(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        values: *const dnsdist_ffi_raw_value_t,
        valuesCount: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_spoof_packet(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        rawresponse: *const ::std::os::raw::c_char,
        len: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_max_returned_ttl(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        max: u32,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_restartable(dq: *mut dnsdist_ffi_dnsquestion_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_alternate_name(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        alternateName: *const ::std::os::raw::c_char,
        alternateNameSize: usize,
        tag: *const ::std::os::raw::c_char,
        tagSize: usize,
        tagValue: *const ::std::os::raw::c_char,
        tagValueSize: usize,
        formerNameTagName: *const ::std::os::raw::c_char,
        formerNameTagSize: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_servers_list_get_count(list: *const dnsdist_ffi_servers_list_t) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_servers_list_get_server(
        list: *const dnsdist_ffi_servers_list_t,
        idx: usize,
        out: *mut *const dnsdist_ffi_server_t,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_servers_list_chashed(
        list: *const dnsdist_ffi_servers_list_t,
        dq: *const dnsdist_ffi_dnsquestion_t,
        hash: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_servers_list_whashed(
        list: *const dnsdist_ffi_servers_list_t,
        dq: *const dnsdist_ffi_dnsquestion_t,
        hash: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_get_outstanding(server: *const dnsdist_ffi_server_t) -> u64;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_is_up(server: *const dnsdist_ffi_server_t) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_get_name(
        server: *const dnsdist_ffi_server_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_get_name_with_addr(
        server: *const dnsdist_ffi_server_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_get_weight(
        server: *const dnsdist_ffi_server_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_get_order(
        server: *const dnsdist_ffi_server_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_server_get_latency(server: *const dnsdist_ffi_server_t) -> f64;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_set_min_ttl(dr: *mut dnsdist_ffi_dnsresponse_t, min: u32);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_set_max_ttl(dr: *mut dnsdist_ffi_dnsresponse_t, max: u32);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_limit_ttl(
        dr: *mut dnsdist_ffi_dnsresponse_t,
        min: u32,
        max: u32,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_set_max_returned_ttl(
        dr: *mut dnsdist_ffi_dnsresponse_t,
        max: u32,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_clear_records_type(
        dr: *mut dnsdist_ffi_dnsresponse_t,
        qtype: u16,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_rebase(
        dr: *mut dnsdist_ffi_dnsresponse_t,
        initialName: *const ::std::os::raw::c_char,
        initialNameSize: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_get_stale_cache_hit(
        dnsResponse: *const dnsdist_ffi_dnsresponse_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_get_restart_count(
        dnsResponse: *const dnsdist_ffi_dnsresponse_t,
    ) -> u8;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_set_async(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        asyncID: u16,
        queryID: u16,
        timeoutMs: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_set_async(
        dq: *mut dnsdist_ffi_dnsquestion_t,
        asyncID: u16,
        queryID: u16,
        timeoutMs: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_resume_from_async(
        asyncID: u16,
        queryID: u16,
        tag: *const ::std::os::raw::c_char,
        tagSize: usize,
        tagValue: *const ::std::os::raw::c_char,
        tagValueSize: usize,
        useCache: bool,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_drop_from_async(asyncID: u16, queryID: u16) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_set_answer_from_async(
        asyncID: u16,
        queryID: u16,
        raw: *const ::std::os::raw::c_char,
        rawSize: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_set_rcode_from_async(
        asyncID: u16,
        queryID: u16,
        rcode: u8,
        clearAnswers: bool,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_resume_from_async_with_alternate_name(
        asyncID: u16,
        queryID: u16,
        alternateName: *const ::std::os::raw::c_char,
        alternateNameSize: usize,
        tag: *const ::std::os::raw::c_char,
        tagSize: usize,
        tagValue: *const ::std::os::raw::c_char,
        tagValueSize: usize,
        formerNameTagName: *const ::std::os::raw::c_char,
        formerNameTagSize: usize,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_proxy_protocol_value {
    pub value: *const ::std::os::raw::c_char,
    pub size: u16,
    pub type_: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dnsdist_ffi_proxy_protocol_value"]
        [::std::mem::size_of::<dnsdist_ffi_proxy_protocol_value>() - 16usize];
    ["Alignment of dnsdist_ffi_proxy_protocol_value"]
        [::std::mem::align_of::<dnsdist_ffi_proxy_protocol_value>() - 8usize];
    ["Offset of field: dnsdist_ffi_proxy_protocol_value::value"]
        [::std::mem::offset_of!(dnsdist_ffi_proxy_protocol_value, value) - 0usize];
    ["Offset of field: dnsdist_ffi_proxy_protocol_value::size"]
        [::std::mem::offset_of!(dnsdist_ffi_proxy_protocol_value, size) - 8usize];
    ["Offset of field: dnsdist_ffi_proxy_protocol_value::type_"]
        [::std::mem::offset_of!(dnsdist_ffi_proxy_protocol_value, type_) - 10usize];
};
pub type dnsdist_ffi_proxy_protocol_value_t = dnsdist_ffi_proxy_protocol_value;
unsafe extern "C" {
    pub fn dnsdist_ffi_generate_proxy_protocol_payload(
        addrSize: usize,
        srcAddr: *const ::std::os::raw::c_void,
        dstAddr: *const ::std::os::raw::c_void,
        srcPort: u16,
        dstPort: u16,
        tcp: bool,
        valuesCount: usize,
        values: *const dnsdist_ffi_proxy_protocol_value_t,
        out: *mut ::std::os::raw::c_void,
        outSize: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_generate_proxy_protocol_payload(
        dq: *const dnsdist_ffi_dnsquestion_t,
        valuesCount: usize,
        values: *const dnsdist_ffi_proxy_protocol_value_t,
        out: *mut ::std::os::raw::c_void,
        outSize: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_add_proxy_protocol_values(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        valuesCount: usize,
        values: *const dnsdist_ffi_proxy_protocol_value_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_get_proxy_protocol_values(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        out: *mut *const dnsdist_ffi_proxy_protocol_value_t,
    ) -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_domain_list_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_address_list_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_address_list_get(
        list: *const dnsdist_ffi_address_list_t,
        idx: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_address_list_free(arg1: *mut dnsdist_ffi_address_list_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_domain_list_get(
        list: *const dnsdist_ffi_domain_list_t,
        idx: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_domain_list_free(arg1: *mut dnsdist_ffi_domain_list_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_packetcache_get_domain_list_by_addr(
        poolName: *const ::std::os::raw::c_char,
        addr: *const ::std::os::raw::c_char,
        out: *mut *mut dnsdist_ffi_domain_list_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_packetcache_get_address_list_by_domain(
        poolName: *const ::std::os::raw::c_char,
        domain: *const ::std::os::raw::c_char,
        out: *mut *mut dnsdist_ffi_address_list_t,
    ) -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_ring_entry_list_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_is_response(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_age(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> f64;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_name(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_type(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_requestor(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_backend(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_protocol(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u8;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_size(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_latency(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_id(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_rcode(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u8;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_aa(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_rd(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_tc(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_ancount(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_nscount(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_arcount(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_has_mac_address(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_get_mac_address(
        list: *const dnsdist_ffi_ring_entry_list_t,
        idx: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_entry_list_free(arg1: *mut dnsdist_ffi_ring_entry_list_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_get_entries(out: *mut *mut dnsdist_ffi_ring_entry_list_t) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_get_entries_by_addr(
        addr: *const ::std::os::raw::c_char,
        out: *mut *mut dnsdist_ffi_ring_entry_list_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_ring_get_entries_by_mac(
        addr: *const ::std::os::raw::c_char,
        out: *mut *mut dnsdist_ffi_ring_entry_list_t,
    ) -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_network_endpoint_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_endpoint_new(
        path: *const ::std::os::raw::c_char,
        pathSize: usize,
        out: *mut *mut dnsdist_ffi_network_endpoint_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_endpoint_is_valid(
        endpoint: *const dnsdist_ffi_network_endpoint_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_endpoint_send(
        endpoint: *const dnsdist_ffi_network_endpoint_t,
        payload: *const ::std::os::raw::c_char,
        payloadSize: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_endpoint_free(endpoint: *mut dnsdist_ffi_network_endpoint_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_dnspacket_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_parse(
        packet: *const ::std::os::raw::c_char,
        packetSize: usize,
        out: *mut *mut dnsdist_ffi_dnspacket_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_qname_raw(
        packet: *const dnsdist_ffi_dnspacket_t,
        qname: *mut *const ::std::os::raw::c_char,
        qnameSize: *mut usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_qtype(packet: *const dnsdist_ffi_dnspacket_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_qclass(packet: *const dnsdist_ffi_dnspacket_t) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_records_count_in_section(
        packet: *const dnsdist_ffi_dnspacket_t,
        section: u8,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_record_name_raw(
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
        name: *mut *const ::std::os::raw::c_char,
        nameSize: *mut usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_record_type(
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_record_class(
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_record_ttl(
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
    ) -> u32;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_record_content_length(
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_record_content_offset(
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_get_name_at_offset_raw(
        packet: *const ::std::os::raw::c_char,
        packetSize: usize,
        offset: usize,
        name: *mut ::std::os::raw::c_char,
        nameSize: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_parse_a_record(
        raw: *const ::std::os::raw::c_char,
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
        addr: *mut ::std::os::raw::c_char,
        addrSize: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_parse_aaaa_record(
        raw: *const ::std::os::raw::c_char,
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
        addr: *mut ::std::os::raw::c_char,
        addrSize: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_parse_address_record(
        raw: *const ::std::os::raw::c_char,
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
        addr: *mut ::std::os::raw::c_char,
        addrSize: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_parse_cname_record(
        raw: *const ::std::os::raw::c_char,
        packet: *const dnsdist_ffi_dnspacket_t,
        idx: usize,
        name: *mut ::std::os::raw::c_char,
        nameSize: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnspacket_free(arg1: *mut dnsdist_ffi_dnspacket_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_metric_declare(
        name: *const ::std::os::raw::c_char,
        nameLen: usize,
        type_: *const ::std::os::raw::c_char,
        description: *const ::std::os::raw::c_char,
        customName: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_metric_inc(metricName: *const ::std::os::raw::c_char, metricNameLen: usize);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_metric_inc_by(
        metricName: *const ::std::os::raw::c_char,
        metricNameLen: usize,
        value: u64,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_metric_dec(metricName: *const ::std::os::raw::c_char, metricNameLen: usize);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_metric_set(
        metricName: *const ::std::os::raw::c_char,
        metricNameLen: usize,
        value: f64,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_metric_get(
        metricName: *const ::std::os::raw::c_char,
        metricNameLen: usize,
        isCounter: bool,
    ) -> f64;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_network_message_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_message_get_payload(
        msg: *const dnsdist_ffi_network_message_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_message_get_payload_size(
        msg: *const dnsdist_ffi_network_message_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_network_message_get_endpoint_id(
        msg: *const dnsdist_ffi_network_message_t,
    ) -> u16;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dynamic_blocks_add(
        address: *const ::std::os::raw::c_char,
        message: *const ::std::os::raw::c_char,
        action: u8,
        duration: ::std::os::raw::c_uint,
        clientIPMask: u8,
        clientIPPortMask: u8,
        tagKey: *const ::std::os::raw::c_char,
        tagValue: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dynamic_blocks_smt_add(
        suffix: *const ::std::os::raw::c_char,
        message: *const ::std::os::raw::c_char,
        action: u8,
        duration: ::std::os::raw::c_uint,
        tagKey: *const ::std::os::raw::c_char,
        tagValue: *const ::std::os::raw::c_char,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_dynamic_block_entry {
    pub key: *mut ::std::os::raw::c_char,
    pub reason: *mut ::std::os::raw::c_char,
    pub blockedQueries: u64,
    pub remainingTime: u64,
    pub action: u8,
    pub ebpf: bool,
    pub warning: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dnsdist_ffi_dynamic_block_entry"]
        [::std::mem::size_of::<dnsdist_ffi_dynamic_block_entry>() - 40usize];
    ["Alignment of dnsdist_ffi_dynamic_block_entry"]
        [::std::mem::align_of::<dnsdist_ffi_dynamic_block_entry>() - 8usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::key"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, key) - 0usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::reason"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, reason) - 8usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::blockedQueries"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, blockedQueries) - 16usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::remainingTime"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, remainingTime) - 24usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::action"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, action) - 32usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::ebpf"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, ebpf) - 33usize];
    ["Offset of field: dnsdist_ffi_dynamic_block_entry::warning"]
        [::std::mem::offset_of!(dnsdist_ffi_dynamic_block_entry, warning) - 34usize];
};
pub type dnsdist_ffi_dynamic_block_entry_t = dnsdist_ffi_dynamic_block_entry;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_dynamic_blocks_list_t {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dynamic_blocks_get_entries(
        out: *mut *mut dnsdist_ffi_dynamic_blocks_list_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dynamic_blocks_smt_get_entries(
        out: *mut *mut dnsdist_ffi_dynamic_blocks_list_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dynamic_blocks_list_get(
        list: *const dnsdist_ffi_dynamic_blocks_list_t,
        idx: usize,
    ) -> *const dnsdist_ffi_dynamic_block_entry_t;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dynamic_blocks_list_free(arg1: *mut dnsdist_ffi_dynamic_blocks_list_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_hash(
        seed: u32,
        data: *const ::std::os::raw::c_uchar,
        dataSize: usize,
        caseInsensitive: bool,
    ) -> u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dnsdist_ffi_svc_record_parameters {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_new(
        targetName: *const ::std::os::raw::c_char,
        priority: u16,
        noDefaultALPN: bool,
        out: *mut *mut dnsdist_ffi_svc_record_parameters,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_set_port(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        port: u16,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_set_ech(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        ech: *const ::std::os::raw::c_char,
        echLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_set_additional_param(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        key: u16,
        value: *const ::std::os::raw::c_char,
        valueLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_add_mandatory_param(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        key: u16,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_add_alpn(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        value: *const ::std::os::raw::c_char,
        valueLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_add_ipv4_hint(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        value: *const ::std::os::raw::c_char,
        valueLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_add_ipv6_hint(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
        value: *const ::std::os::raw::c_char,
        valueLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_svc_record_parameters_free(
        parameters: *mut dnsdist_ffi_svc_record_parameters,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_generate_svc_response(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        parametersList: *mut *const dnsdist_ffi_svc_record_parameters,
        parametersListSize: usize,
        ttl: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_meta_begin_key(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        key: *const ::std::os::raw::c_char,
        keyLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_meta_add_str_value_to_key(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        value: *const ::std::os::raw::c_char,
        valueLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_meta_add_int64_value_to_key(
        dnsQuestion: *mut dnsdist_ffi_dnsquestion_t,
        value: i64,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsquestion_meta_end_key(dnsQuestion: *mut dnsdist_ffi_dnsquestion_t);
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_meta_begin_key(
        dnsResponse: *mut dnsdist_ffi_dnsresponse_t,
        key: *const ::std::os::raw::c_char,
        keyLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_meta_add_str_value_to_key(
        dnsResponse: *mut dnsdist_ffi_dnsresponse_t,
        value: *const ::std::os::raw::c_char,
        valueLen: usize,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_meta_add_int64_value_to_key(
        dnsResponse: *mut dnsdist_ffi_dnsresponse_t,
        value: i64,
    );
}
unsafe extern "C" {
    pub fn dnsdist_ffi_dnsresponse_meta_end_key(dnsResponse: *mut dnsdist_ffi_dnsresponse_t);
}
